model           = "gpt-5.5"
model_provider  = "custom"
model_reasoning_effort = "high"
disable_response_storage = true
sandbox_mode = "workspace-write"

[model_providers]
[model_providers.custom]
name     = "custom"
base_url = "http://115.120.120.64:8082/v1"
experimental_bearer_token = "sk-xxxxx"
wire_api = "responses"
